### ISSUE TITLE
S10 Plus camera quality worse than on the stock rom

### ISSUE THREAD

**Issue by nemanjastolee** [ExtremeXT/ExtremeROM#172]
After I installed the rom on my S10 Plus, the camera got worse. Pictures look dull and a bit blurry. On the stock rom, HDR and processing was there and pictures looked good

**Comment by Android-Artisan** [comment]
> After I installed the rom on my S10 Plus, the camera got worse. Pictures look dull and a bit blurry. On the stock rom, HDR and processing was there and pictures looked good

This is probably not a rom issue

Did you try to clean the lens

If still no go back to stock and check

If there on stock go to repair center. It might be due to residue or humidity inside the phone

**Comment by nemanjastolee** [comment]
Yes, I cleaned the lens. Still a bit blurry

**Comment by nemanjastolee** [comment]
![Image](https://github.com/user-attachments/assets/35b931e6-e709-44d2-8b86-e8b3807a2091)
On the right is the stock, on the left is the rom

**Comment by alvixsiyam** [comment]
> ![Image](https://github.com/user-attachments/assets/35b931e6-e709-44d2-8b86-e8b3807a2091) On the right is the stock, on the left is the rom

I did notice the camera appearing blurry but not sure is it because of the rom or the dusts inside.
Can you confirm if the picture looks way too blurry and less detailed for the rom then I might just avoid the repair center.
Regards

**Comment by Mesazane** [comment]
> Pictures look dull

this is probably caused by the vividness bug that was already fixed. I dont know about the blurry part though...

**Comment by nemanjastolee** [comment]
That was the problem on the cracked S10 Plus. I installed the rom on the other S10 Plus and edited the file and picture look a bit better now, but still not as good as the stock rom

**Comment by ExtremeXT** [comment]
Yeah... It's a 6 year old phone after all, Samsung dropped some S10 related camera things from UI 7.
